name: Milwaukeetool Auto Sign

on:
  schedule:
    - cron: '0 1,7 * * *'  # ✅ 北京时间 10:00、16:00 运行

  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 校验北京时间（禁止 23:00~07:00）
      run: |
        # 固定为上海时区，时间绝对准确
        sudo timedatectl set-timezone Asia/Shanghai
        BEIJING_HOUR=$(date +'%H')
        echo "当前北京时间：$BEIJING_HOUR 点"
        
        if [ $BEIJING_HOUR -ge 23 ] || [ $BEIJING_HOUR -lt 7 ]; then
          echo "❌ 当前是夜间 23:00~07:00，任务退出"
          exit 1
        else
          echo "✅ 时间合规，开始签到"
        fi

    - name: Run Sign Script
      env:
        MILWAUKEETOOL_CLIENT_ID: ${{ secrets.MILWAUKEETOOL_CLIENT_ID }}
        MILWAUKEETOOL_TOKEN_LIST: ${{ secrets.MILWAUKEETOOL_TOKEN_LIST }}
        WECHAT_WEBHOOK_URL: ${{ secrets.WECHAT_WEBHOOK_URL }}
        DINGTALK_WEBHOOK_URL: ${{ secrets.DINGTALK_WEBHOOK_URL }}
      run: |
        python milwaukeetool-sign.py
