name: JLC Auto Sign

on:
  schedule:
    - cron: '0 2,8 * * *'  # 🔥 固定每天 北京时间 10:00 运行
  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 校验北京时间（禁止 23:00~07:00）
      run: |
        BEIJING_HOUR=$(date -u -d '+8 hours' +'%H')
        echo "当前北京时间：$BEIJING_HOUR 点"
        
        if [ $BEIJING_HOUR -ge 23 ] || [ $BEIJING_HOUR -lt 7 ]; then
          echo "❌ 当前是 23:00~07:00，禁止签到，任务退出"
          exit 1
        else
          echo "✅ 当前时间合规，允许签到"
        fi

    - name: 执行签到脚本
      env:
        TOKEN_LIST: ${{ secrets.TOKEN_LIST }}
        DINGTALK_WEBHOOK_URL: ${{ secrets.DINGTALK_WEBHOOK_URL }}
      run: |
        python main.py
